package com.konnisan.dewuauto.automation

enum class AutomationState {
    IDLE,
    VERIFYING_LICENSE,
    WAITING_HOME,
    OPENING_PROFILE,
    WAITING_PROFILE,
    OPENING_BRAND_COOPERATION,
    WAITING_BRAND_PAGE,
    APPLYING_INITIAL_SORT,
    APPLYING_CATEGORY,
    SCANNING_TASKS,
    SCROLLING_TASKS,
    FINISHED,
    PAUSED_FOR_SECURITY,
    ERROR,
}
